// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_ci_srv_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Upload service

type UploadService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Upload_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Upload_PingPongService, error)
	//文件上传
	FileUpload(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*Response, error)
}

type uploadService struct {
	c    client.Client
	name string
}

func NewUploadService(name string, c client.Client) UploadService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.ci.srv.upload"
	}
	return &uploadService{
		c:    c,
		name: name,
	}
}

func (c *uploadService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Upload.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Upload_StreamService, error) {
	req := c.c.NewRequest(c.name, "Upload.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &uploadServiceStream{stream}, nil
}

type Upload_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type uploadServiceStream struct {
	stream client.Stream
}

func (x *uploadServiceStream) Close() error {
	return x.stream.Close()
}

func (x *uploadServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uploadService) PingPong(ctx context.Context, opts ...client.CallOption) (Upload_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Upload.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &uploadServicePingPong{stream}, nil
}

type Upload_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type uploadServicePingPong struct {
	stream client.Stream
}

func (x *uploadServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *uploadServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *uploadServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uploadService) FileUpload(ctx context.Context, in *FileRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Upload.FileUpload", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Upload service

type UploadHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Upload_StreamStream) error
	PingPong(context.Context, Upload_PingPongStream) error
	//文件上传
	FileUpload(context.Context, *FileRequest, *Response) error
}

func RegisterUploadHandler(s server.Server, hdlr UploadHandler, opts ...server.HandlerOption) error {
	type upload interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
		FileUpload(ctx context.Context, in *FileRequest, out *Response) error
	}
	type Upload struct {
		upload
	}
	h := &uploadHandler{hdlr}
	return s.Handle(s.NewHandler(&Upload{h}, opts...))
}

type uploadHandler struct {
	UploadHandler
}

func (h *uploadHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.UploadHandler.Call(ctx, in, out)
}

func (h *uploadHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.UploadHandler.Stream(ctx, m, &uploadStreamStream{stream})
}

type Upload_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type uploadStreamStream struct {
	stream server.Stream
}

func (x *uploadStreamStream) Close() error {
	return x.stream.Close()
}

func (x *uploadStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *uploadHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.UploadHandler.PingPong(ctx, &uploadPingPongStream{stream})
}

type Upload_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type uploadPingPongStream struct {
	stream server.Stream
}

func (x *uploadPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *uploadPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *uploadPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *uploadPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *uploadPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *uploadHandler) FileUpload(ctx context.Context, in *FileRequest, out *Response) error {
	return h.UploadHandler.FileUpload(ctx, in, out)
}
