// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upload/upload.proto

package go_micro_ci_srv_upload

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件上传Request
type FileRequest struct {
	//文件名
	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	//文件大小
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	//文件内容
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{4}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{5}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{6}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_5508b024e4d0ced2, []int{7}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "go.micro.ci.srv.upload.FileRequest")
	proto.RegisterType((*Message)(nil), "go.micro.ci.srv.upload.Message")
	proto.RegisterType((*Request)(nil), "go.micro.ci.srv.upload.Request")
	proto.RegisterType((*Response)(nil), "go.micro.ci.srv.upload.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.ci.srv.upload.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.ci.srv.upload.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.ci.srv.upload.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.ci.srv.upload.Pong")
}

func init() { proto.RegisterFile("proto/upload/upload.proto", fileDescriptor_5508b024e4d0ced2) }

var fileDescriptor_5508b024e4d0ced2 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0xad, 0x9b, 0x90, 0x96, 0x81, 0x45, 0x19, 0xa1, 0xaa, 0x84, 0x02, 0x91, 0xd9, 0xa4, 0x1b,
	0x53, 0xc1, 0x11, 0x90, 0xd8, 0xf0, 0x11, 0x04, 0xf5, 0x00, 0xa6, 0x35, 0x96, 0x45, 0x12, 0x97,
	0x38, 0x45, 0x82, 0xbb, 0x72, 0x17, 0x14, 0xc7, 0x81, 0x0a, 0x35, 0x52, 0x57, 0x9e, 0xf1, 0x7b,
	0x6f, 0x3e, 0x4f, 0x03, 0x47, 0xcb, 0x42, 0x97, 0xfa, 0x62, 0xb5, 0x4c, 0x35, 0x5f, 0xb8, 0x87,
	0xd9, 0x3f, 0x1c, 0x4a, 0xcd, 0x32, 0x35, 0x2f, 0x34, 0x9b, 0x2b, 0x66, 0x8a, 0x0f, 0x56, 0xa3,
	0xf4, 0x09, 0xf6, 0x6e, 0x54, 0x2a, 0x12, 0xf1, 0xbe, 0x12, 0xa6, 0xc4, 0x10, 0xfa, 0xaf, 0x2a,
	0x15, 0x0f, 0x3c, 0x13, 0x23, 0x12, 0x91, 0x78, 0x37, 0xf9, 0xcd, 0x11, 0xc1, 0x37, 0xea, 0x4b,
	0x8c, 0xba, 0x11, 0x89, 0xbd, 0xc4, 0xc6, 0xd5, 0xdf, 0x82, 0x97, 0x7c, 0xe4, 0x45, 0x24, 0xde,
	0x4f, 0x6c, 0x4c, 0x8f, 0xa1, 0x77, 0x2f, 0x8c, 0xe1, 0x52, 0xe0, 0x00, 0x3c, 0xc3, 0x3f, 0x5d,
	0xa5, 0x2a, 0xa4, 0x27, 0xd0, 0x6b, 0x7a, 0x21, 0xf8, 0xf9, 0x5f, 0x1f, 0x1b, 0xd3, 0x31, 0xf4,
	0x13, 0x61, 0x96, 0x3a, 0x37, 0x56, 0x9c, 0x19, 0xd9, 0x88, 0x33, 0x23, 0x69, 0x0c, 0x83, 0xe7,
	0xb2, 0x10, 0x3c, 0x53, 0xb9, 0x6c, 0xaa, 0x1c, 0xc2, 0xce, 0x5c, 0xaf, 0xf2, 0xd2, 0xf2, 0xbc,
	0xa4, 0x4e, 0xe8, 0x04, 0x0e, 0xd6, 0x98, 0xae, 0xe0, 0x66, 0xea, 0x29, 0xf8, 0x8f, 0x2a, 0x97,
	0x38, 0x84, 0xc0, 0x94, 0x85, 0x7e, 0x13, 0x0e, 0x76, 0x99, 0xc5, 0x75, 0x3b, 0x7e, 0xf9, 0xdd,
	0x85, 0x60, 0x66, 0xcd, 0xc4, 0x5b, 0xf0, 0xaf, 0x79, 0x9a, 0xe2, 0x19, 0xdb, 0xec, 0x36, 0x73,
	0x43, 0x87, 0x51, 0x3b, 0xa1, 0x9e, 0x95, 0x76, 0x90, 0x43, 0x50, 0xaf, 0x80, 0x71, 0x1b, 0xfb,
	0xbf, 0x19, 0xe1, 0x64, 0x0b, 0x66, 0xd3, 0x60, 0x4a, 0xf0, 0x0e, 0xfa, 0xd5, 0xea, 0x76, 0xbd,
	0x71, 0x9b, 0xb4, 0x62, 0x84, 0xed, 0xa8, 0xce, 0x25, 0xed, 0xc4, 0x64, 0x4a, 0x70, 0x06, 0x50,
	0x9d, 0x92, 0xf3, 0xe2, 0xbc, 0x4d, 0xb1, 0x76, 0x6e, 0xdb, 0xf8, 0xf0, 0x12, 0xd8, 0x03, 0xbe,
	0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xee, 0xef, 0x47, 0xdd, 0x02, 0x00, 0x00,
}
